### ISSUE TITLE
You exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by pvpb0t** [Blarc/ai-commits-intellij-plugin#31] opened 2023-04-16 11:02 UTC
Even with only one file with barely any diff it still says "You exceeded your current quota, please check your plan and billing details"
I have chatgpt free but there should be an option

**Comment by Blarc** [comment] 2023-04-16 13:43
I am not sure if I correctly understand your problem. The plugin calls the OpenAI API for generating commit message, which is not free. If you have gotten `You exceeded your current quota, please check your plan and billing details` error, it means that the API key you provided in the plugin's settings does not have any more tokens available for usage.

If you know of another way to call the OpenAI API (or maybe some other alternative) for free, I would gladly add the support.

**Comment by Blarc** [comment] 2023-04-18 19:26
Hey @cforce. What do you mean by chat prompt? The chatgpt is free, while the OpenAI API is not (as far as I understand).

**Comment by cforce** [comment] 2023-04-18 22:48
I would rather use the Azure OpenAi offering but the plug-in needs to add cfg support for url,  Model name and model type to target an Azure Gpt3Turbo model

**Comment by ioanlucut** [comment] 2023-07-19 09:36
> PS2: I should probably explicitly mention somewhere that the plugin uses OpenAI API (that is not free).

I think it's very important. Maybe you can tell us what are the pricing for a full-time dev per month? Otherwise, it's hard to estimate.

**Comment by Blarc** [comment] 2023-07-19 12:25
> > PS2: I should probably explicitly mention somewhere that the plugin uses OpenAI API (that is not free).
> 
> I think it's very important. Maybe you can tell us what are the pricing for a full-time dev per month? Otherwise, it's hard to estimate.

I think that depends a lot on the developer. As in how much he commits daily and how big changes does he make. I would need to track users' usage in order to get an average, which I don't want to do.

The pricing for OpenAI can be found [here](https://openai.com/pricing).

**Comment by Spidlace** [comment] 2023-12-14 13:49
Hello @Blarc 

Is it possible to use token generate by web API (when we have plan on chatGPT but not API) ?
The token can be found here : https://chat.openai.com/api/auth/session

When we "Verify",   we have confirmation message "Open AI configuration is valid" but when I try to generate commit I have "You exceeded your current quote...."

**Comment by Blarc** [comment] 2023-12-14 16:36
Hi @Spidlace,

according to [this](https://community.openai.com/t/can-i-have-the-same-service-using-a-chatgpt-plus-or-an-openai-subscription/370603), I believe you need a different API key.

You can maybe test this, by making a request via curl: https://platform.openai.com/docs/api-reference/making-requests.

**Comment by Blarc** [comment] 2024-03-11 17:41
Duplicate of https://github.com/Blarc/ai-commits-intellij-plugin/issues/93.

**Closed by Blarc** 2024-03-11 17:41 UTC
