### ISSUE TITLE
Language Change

### ISSUE THREAD

**Issue by mesofranico** [Blarc/ai-commits-intellij-plugin#183] opened 2024-05-30 11:21 UTC
I use Portuguese but English is used all time
![aicommit](https://github.com/Blarc/ai-commits-intellij-plugin/assets/8009556/1b01cc44-a4fb-4842-bbcb-13bcb67445b5)
![commitai](https://github.com/Blarc/ai-commits-intellij-plugin/assets/8009556/9fed17f6-c68b-4c88-bcdd-4812856bd836)

**Comment by Blarc** [comment] 2024-05-30 14:24
Duplicate of https://github.com/Blarc/ai-commits-intellij-plugin/issues/181. 

You can maybe try creating a custom prompt in Portuguese?

**Closed by Blarc** 2024-05-30 14:24 UTC
